### ISSUE TITLE
Strange Error When Running Cargo Doc

### ISSUE THREAD

**Issue by gregelenbaas** [actix/actix#189]
I can't run cargo doc on my project using actix-web due to an error documenting actix. I am running rust 1.31 and have my project set to edition 2018:

```
C:\Users\GregElenbaas\workspace\walkwiki>cargo doc --open
 Documenting actix v0.7.9
error[E0275]: overflow evaluating the requirement `std::ptr::Unique<std::vec::Vec<u8>>: std::marker::Send`
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: required because it appears within the type `alloc::raw_vec::RawVec<std::vec::Vec<u8>>`
  = note: required because it appears within the type `std::vec::Vec<std::vec::Vec<u8>>`
  = note: required because it appears within the type `mio::sys::windows::buffer_pool::BufferPool`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Mutex<mio::sys::windows::buffer_pool::BufferPool>`
  = note: required because it appears within the type `mio::sys::windows::selector::SelectorInner`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<mio::sys::windows::selector::SelectorInner>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `lazycell::AtomicLazyCell<std::sync::Arc<mio::sys::windows::selector::SelectorInner>>`
  = note: required because it appears within the type `mio::sys::windows::selector::Binding`
  = note: required because it appears within the type `mio::sys::windows::selector::ReadyBinding`
  = note: required because it appears within the type `mio::sys::windows::udp::Inner`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Mutex<mio::sys::windows::udp::Inner>`
  = note: required because it appears within the type `mio::sys::windows::udp::Io`
  = note: required because of the requirements on the impl of `std::marker::Send` for `mio::sys::windows::from_raw_arc::FromRawArc<mio::sys::windows::udp::Io>`
  = note: required because it appears within the type `mio::sys::windows::udp::Imp`
  = note: required because it appears within the type `mio::sys::windows::udp::UdpSocket`
  = note: required because it appears within the type `mio::net::udp::UdpSocket`
  = note: required because it appears within the type `std::option::Option<mio::net::udp::UdpSocket>`
  = note: required because it appears within the type `tokio_reactor::PollEvented<mio::net::udp::UdpSocket>`
  = note: required because it appears within the type `tokio::net::UdpSocket`  = note: required because it appears within the type `std::option::Option<tokio::net::UdpSocket>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::trust_dns_proto::udp::udp_client_stream::SingleUseUdpSocket`
  = note: required because it appears within the type `tokio_timer::Timeout<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::udp_client_stream::SingleUseUdpSocket>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse`
  = note: required because it appears within the type `std::option::Option<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `futures::lock::Lock<std::option::Option<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>>`
  = note: required because it appears within the type `futures::sync::oneshot::Inner<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<futures::sync::oneshot::Inner<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>>`
  = note: required because it appears within the type `futures::Sender<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::trust_dns_proto::xfer::OneshotDnsRequest<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `futures::sync::mpsc::Inner<actors::resolver::trust_dns_resolver::trust_dns_proto::xfer::OneshotDnsRequest<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<futures::sync::mpsc::Inner<actors::resolver::trust_dns_resolver::trust_dns_proto::xfer::OneshotDnsRequest<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>>>`
  = note: required because it appears within the type `futures::sync::mpsc::Sender<actors::resolver::trust_dns_resolver::trust_dns_proto::xfer::OneshotDnsRequest<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>>`
  = note: required because it appears within the type `futures::sync::mpsc::UnboundedSender<actors::resolver::trust_dns_resolver::trust_dns_proto::xfer::OneshotDnsRequest<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::trust_dns_proto::xfer::DnsRequestStreamHandle<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::trust_dns_proto::xfer::BufDnsRequestStreamHandle<actors::resolver::trust_dns_resolver::trust_dns_proto::udp::UdpResponse>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandleConnected`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandleInner`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Mutex<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandleInner>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<std::sync::Mutex<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandleInner>>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::name_server_pool::NameServer<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<actors::resolver::trust_dns_resolver::name_server_pool::NameServer<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>>`
  = note: required because it appears within the type `alloc::raw_vec::RawVec<actors::resolver::trust_dns_resolver::name_server_pool::NameServer<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>>`
  = note: required because it appears within the type `std::vec::Vec<actors::resolver::trust_dns_resolver::name_server_pool::NameServer<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Mutex<std::vec::Vec<actors::resolver::trust_dns_resolver::name_server_pool::NameServer<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>>>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<std::sync::Mutex<std::vec::Vec<actors::resolver::trust_dns_resolver::name_server_pool::NameServer<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>>>>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::name_server_pool::NameServerPool<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::trust_dns_proto::RetryDnsHandle<actors::resolver::trust_dns_resolver::name_server_pool::NameServerPool<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::lookup::LookupEither<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::lookup_state::CachingClient<actors::resolver::trust_dns_resolver::lookup::LookupEither<actors::resolver::trust_dns_resolver::name_server_pool::ConnectionHandle, actors::resolver::trust_dns_resolver::name_server_pool::StandardConnection>>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::lookup::LookupFuture`
  = note: required because it appears within the type `std::option::Option<actors::resolver::trust_dns_resolver::lookup::LookupFuture>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `futures::lock::Lock<std::option::Option<actors::resolver::trust_dns_resolver::lookup::LookupFuture>>`
  = note: required because it appears within the type `futures::sync::oneshot::Inner<actors::resolver::trust_dns_resolver::lookup::LookupFuture>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<futures::sync::oneshot::Inner<actors::resolver::trust_dns_resolver::lookup::LookupFuture>>`
  = note: required because it appears within the type `futures::Sender<actors::resolver::trust_dns_resolver::lookup::LookupFuture>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::async_resolver::Request`
  = note: required because of the requirements on the impl of `std::marker::Send` for `futures::sync::mpsc::Inner<actors::resolver::trust_dns_resolver::async_resolver::Request>`
  = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<futures::sync::mpsc::Inner<actors::resolver::trust_dns_resolver::async_resolver::Request>>`
  = note: required because it appears within the type `futures::sync::mpsc::Sender<actors::resolver::trust_dns_resolver::async_resolver::Request>`
  = note: required because it appears within the type `futures::sync::mpsc::UnboundedSender<actors::resolver::trust_dns_resolver::async_resolver::Request>`
  = note: required because it appears within the type `actors::resolver::trust_dns_resolver::AsyncResolver`
  = note: required because it appears within the type `std::option::Option<actors::resolver::trust_dns_resolver::AsyncResolver>`
  = note: required because it appears within the type `actors::resolver::Resolver`

error: Could not document `actix`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name actix C:\Users\GregElenbaas\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-0.7.9\src/lib.rs --cap-lints allow --color always -o C:\Users\GregElenbaas\workspace\walkwiki\target\doc --cfg "feature=\"default\"" --cfg "feature=\"resolver\"" --cfg
"feature=\"signal\"" --cfg "feature=\"tokio-signal\"" --cfg "feature=\"trust-dns-proto\"" --cfg "feature=\"trust-dns-resolver\"" -L dependency=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps --extern actix_derive=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\actix_derive-bd8466e5a3f5ab2e.dll --extern bitflags=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libbitflags-61bd86b3d3426acc.rmeta --extern bytes=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libbytes-788e68bf23e600c4.rmeta --extern crossbeam_channel=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libcrossbeam_channel-5710b2ac07374b9a.rmeta --extern failure=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libfailure-16119ac25b7925ea.rmeta --extern fnv=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libfnv-b0a886f693aec69a.rmeta --extern futures=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libfutures-827c59f67b54d9b1.rmeta --extern log=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\liblog-af14f4756be5f5ff.rmeta --extern parking_lot=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libparking_lot-a37e1f717009eefe.rmeta --extern smallvec=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libsmallvec-f81bda96822d22d1.rmeta --extern tokio_codec=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio_codec-97bbab1c0e18efad.rmeta --extern tokio_executor=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio_executor-b06cad3c378d2a78.rmeta --extern tokio=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio-8f497d79da1555f5.rmeta --extern tokio_io=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio_io-900bba5937a286f6.rmeta --extern tokio_reactor=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio_reactor-bfd49ad96ed059ee.rmeta --extern tokio_signal=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio_signal-2aa4201aeb82222b.rmeta --extern tokio_tcp=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio_tcp-4dfe06b6d9c86800.rmeta --extern tokio_timer=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtokio_timer-280ccb9444c2ed1f.rmeta --extern trust_dns_proto=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtrust_dns_proto-c53fd955f53bbe34.rmeta --extern trust_dns_resolver=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libtrust_dns_resolver-ac33edc762adeac4.rmeta --extern uuid=C:\Users\GregElenbaas\workspace\walkwiki\target\debug\deps\libuuid-df9acd76c1660055.rmeta` (exit code: 1)
```

**Comment by gregelenbaas** [comment]
Thanks for the quick response! Do I add that to my code or to actix?

**Comment by DoumanAsh** [comment]
For now you can add it in your code, I'm not sure yet how we should resolve it

**Comment by gregelenbaas** [comment]
Adding the recursion limit line doesn't seem to work. I added the recursion limit declaration at the top of my main.rs file, was I supposed to add it somewhere else? I found a post that this seems to be a known issue for other projects as well. https://internals.rust-lang.org/t/pre-rfc-changing-how-the-macro-recursion-limit-works/5170

**Comment by DoumanAsh** [comment]
>Adding the recursion limit line doesn't seem to work

That's actually what helped me when I tried to check this problem, I'm not sure why it wouldn't work.

The thing with problem is that I'm not sure where would be right place to put it at all

**Comment by novacrazy** [comment]
This is still an issue, unfortunately. Makes it impossible to fully document a project that uses actix/actix-web.

**Comment by JakubKoralewski** [comment]
`error: could not document 'actix.'`: [error snippet](https://gist.github.com/JakubKoralewski/5d49d961e2ea09b6614b6d802ce2bec4)

**Comment by fafhrd91** [comment]
https://docs.rs/actix/0.7.9/actix/

**Comment by novacrazy** [comment]
I don't see how linking to docs.rs is a solution.

Has documenting actix as a dependency been fixed? Perhaps it was fixed on rustdoc's side?

Not being able to use local documentation of potentially hundreds of other interlinked crates because actix 0.7.9 has excessive recursion makes it difficult to work with.

I've been fairly lucky in the past because actix depends on so many thing it's usually documented close to last, so I can at least have 90% of my dependencies documented before actix causes errors, but still.

Does perhaps actix 1.0 provide a real solution via greater molecularity or a design that uses less type recursion?

**Comment by fafhrd91** [comment]
both actix and actix-web master works for me. 

rustc 1.33.0 (2aa4c46cf 2019-02-28)

**Comment by JakubKoralewski** [comment]
Doesn't work for me:
```
cargo 1.33.0 (f099fe94b 2019-02-12)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
actix v0.7.9
actix-web v0.7.19
```

**Comment by fafhrd91** [comment]
0.7 is in maintenance mode. you can submit PR though

**Comment by Bobo1239** [comment]
I've investigated this a bit more and apparently the issue only happens on Windows (and still happens with the latest code in master). Opened a PR to fix this: https://github.com/actix/actix-net/pull/14

**Comment by photex** [comment]
Still happening on master for me.
